### ISSUE TITLE
Update Webservice (Proxy) URL - TimeRange (used in Powersearch)

### ISSUE THREAD

**Issue by treml05** [EEXCESS/privacy-proxy#2]
The PowerSearch provides a TimeRange as Input but still gets connected to the Privacy-Proxy-1.0, which doesn't know any TimeRange.

The latest version of the Privacy Proxy would be helpful. (Deployment-Link)

Screenshot
https://www.dropbox.com/s/taex2dc8lpj6i14/Screenshot%202015-08-11%2012.07.02.png?dl=0

**Comment by schloett** [comment]
works for me with the dev-server. Are you sure, you are using the right format? Should be:
timeRange:{
    start:" xxxx"
    end:"xxxx"
}
(Closing the issue, since I assume it was a problem with the format. If not, then please reopen)
