### ISSUE TITLE
Connection possible via https?

### ISSUE THREAD

**Issue by schloett** [EEXCESS/privacy-proxy#3]
For the chrome-extension (and I guess for other clients as well), it would be nice, if requests to the privacy-proxy could be made via https instead of http (and it would also support privacy ;)).

In the chrome-extension, we face the problem, that mixed content requests are not allowed. That is, when a page was loaded via https, ajax-requests within that page must also use https.

**Comment by ThomasCerq** [comment]
If I understood correctly the documentation, enabling https requests has a lot to do with the configuration of the TomCat server. If it's correct, then Thomas O. would be more able to deal with this issue.

**Comment by schloett** [comment]
Yes, sorry my bad, I will contact Thomas O.

**Comment by jr-dig-orgel** [comment]
I will check if its possible to activate https on the dev server
